obj-$(CONFIG_RPMSG)	+= virtio_rpmsg_bus.o
obj-$(CONFIG_RPMSG_CDEV)	+= rpmsg_cdev.o
obj-$(CONFIG_RPMSG_CDEV)	+= rpmsg_rvc.o
obj-$(CONFIG_RPMSG_CDEV)	+= adayo_debug.o
obj-$(CONFIG_RPMSG_CDEV)	+= rvc_gui_show.o