obj-$(CONFIG_VIDEO_SIRFSOC_CVD)   += cvd.o
obj-$(CONFIG_VIDEO_SIRFSOC_VIP)   += vip_capture.o
obj-$(CONFIG_VIDEO_SIRFSOC_REARVIEW)   += rearview.o
//obj-$(CONFIG_VIDEO_SIRFSOC_VOUT)  += sirfsoc_vout.o
obj-$(CONFIG_VIDEO_SIRFSOC_VOUT)  += sirfsoc_vout_patch.o
