snd-soc-sirf-atlas7-iacc-objs := atlas7-iacc.o
snd-soc-sirf-audio-objs := sirf-audio.o
snd-soc-sirf-audio-port-objs := sirf-audio-port.o
snd-soc-sirf-i2s-objs := sirf-i2s.o
snd-soc-sirf-atlas7-cs42xx8-objs := sirf-atlas7-cs42xx8.o
snd-soc-sirf-usp-objs := sirf-usp.o

obj-$(CONFIG_SND_SOC_SIRF_ATLAS7_IACC) += snd-soc-sirf-atlas7-iacc.o
obj-$(CONFIG_SND_SOC_SIRF_AUDIO) += snd-soc-sirf-audio.o
obj-$(CONFIG_SND_SOC_SIRF_AUDIO_PORT) += snd-soc-sirf-audio-port.o
obj-$(CONFIG_SND_SOC_SIRF_I2S) += snd-soc-sirf-i2s.o
obj-$(CONFIG_SND_SOC_SIRF_ATLAS7_CS42XX8) += snd-soc-sirf-atlas7-cs42xx8.o
obj-$(CONFIG_SND_SOC_SIRF_KALIMBA) += kalimba/
obj-$(CONFIG_SND_SOC_SIRF_KALIMBA_M3) += kalimba-m3/
obj-$(CONFIG_SND_SOC_SIRF_USP) += snd-soc-sirf-usp.o
