/*
 * Copyright (c) 2014-2016, The Linux Foundation. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef _SIRF_ATLAS7_CODEC_H
#define _SIRF_ATLAS7_CODEC_H

#define ANA_PMUCTL1				0x20
#define ANA_PMUCTL2				0x24

#define AUDIO_REF_CTRL				0x38
#define AUDIO_REF_CTRL2				0x3C

#define AUDIO_REGS_I2S_CTRL			0x40
#define AUDIO_REGS_CLK_CTRL			0x44
#define AUDIO_KCODEC_CTRL			0x48
#define AUDIO_DIGMIC_CTRL			0x50
#define AUDIO_DAC_CTRL				0x54
#define AUDIO_CTRL_SPARE_0			0x58
#define AUDIO_ANA_DAC_CTRL0			0x60
#define AUDIO_ANA_REF_CTRL0			0x64

#define AUDIO_ANA_ADC_CTRL0			0x68
#define AUDIO_ANA_ADC_CTRL1			0x6C
#define AUDIO_ANA_ADC_CTRL2			0x70
#define AUDIO_ANA_ADC_CTRL3			0x74
#define AUDIO_ANA_ADC_CTRL4			0x78
#define AUDIO_ANA_CAL_CTRL0			0x7C

#define KCODEC_ADC_A_GAIN			0xA0
#define KCODEC_ADC_A_SAMP_RATE			0xAC
#define KCODEC_ADC_B_GAIN			0xBC
#define KCODEC_ADC_B_SAMP_RATE			0xCC

#define KCODEC_CONFIG_EXTENSION2		0xF8
#define KCODEC_CONFIG2_EXTENSION2		0x110
#define KCODEC_CONFIG				0x150
#define KCODEC_CONFIG2				0x158
#define KCODEC_DAC_A_GAIN			0x164
#define KCODEC_DAC_A_SAMP_RATE			0x16C
#define KCODEC_DAC_B_GAIN			0x174
#define KCODEC_DAC_B_SAMP_RATE			0x17C
#define KCODEC_DAC_C_GAIN			0x184
#define KCODEC_DAC_C_SAMP_RATE			0x188
#define KCODEC_DAC_D_GAIN			0x190
#define KCODEC_DAC_D_SAMP_RATE			0x194

#define KCODEC_DAC_A_DC_OFFSET			0x1E8
#define KCODEC_DAC_B_DC_OFFSET			0x1EC
#define KCODEC_DAC_C_DC_OFFSET			0x1F0
#define KCODEC_DAC_D_DC_OFFSET			0x1F4

#define AUDIO_PLL_CTRL_1			0x230
#define AUDIO_PLL_STATUS			0x250

#define KCODEC_WARP_UPDATE			0x368

#define ANA_MACRO_CLK_TEST_SEL_MASK		(0x3 << 5)
#define ANA_MACRO_CLK_TEST_SEL_SHIFT		5

#define ANA_DIG_MIC_CLK_TEST_EN_MASK		1
#define ANA_DIG_MIC_CLK_TEST_EN_SHIFT		0

#define PMUCTL1_LDO_VAUDIO1V8_EN		(1 << 1)
#define PMUCTL1_VOUT_SEL_LDO_VAUDIO1V8		(1 << 2)
#define PMUCTL1_LDO_VAUDIO2V5_EN		(1 << 4)
#define PMUCTL1_VOUT_SEL_LDO_VAUDIO2V5		(1 << 5)

#define CLKSYNR_NRST				(1 << 12)

#define PMUCTRL2_VBG_TRIM			0xF
#define PMUCTRL2_IREF_TRIM			(0x7 << 4)

#define PMUCTRL2_VBG_TRIM_0XF			0XF

#define AUDIO_ANA_REF_AUDBIAS_IREF_EN		1
#define AUDIO_ANA_REF_AUDBIAS_IREF_TRIM_SHIFT	1
#define AUDIO_ANA_REF_AUDBIAS_VAG_RX_EN		(1 << 4)
#define AUDIO_ANA_REF_AUDBIAS_VAG_TX_EN		(1 << 5)
#define AUDIO_ANA_REF_VGA_IREF_TX_EN		(1 << 8)
#define AUDIO_ANA_REF_AUDBIAS_IREF_TRIM_MASK	(0x7 << 1)

#define AUDIO_REF_BIAS_BG_VTH_TRIM_MASK		0xF
#define AUDIO_REF_BIAS_BG_PTAT_TRIM_MASK	(0xF << 4)
#define AUDIO_REF_BIAS_BG_PTAT_TRIM_SHIFT	4
#define AUDIO_REF_BIAS_BG_VTH_SHIFT		0

#define AUDIO_REF_BOOST_EN_DACBUFF_IREF_MASK	0x3

#define DAC_CLK_EN				(0xF << 6)

#define DAC_RESET_MASK				0xF

#define KCODEC_DAC_EN				1
#define KCODEC2_CONFIG_DAC_A_EN			(1 << 12)
#define KCODEC2_CONFIG_DAC_B_EN			(1 << 13)
#define KCODEC2_CONFIG_DAC_C_EN			(1 << 12)
#define KCODEC2_CONFIG_DAC_D_EN			(1 << 13)

#define AUDIO_ANA_DAC_VGEN_EN_MASK		1
#define AUDIO_ANA_DAC_VGEN_EN_SHIFT		0
#define AUDIO_ANA_DAC_LOUT_EN_MASK		(0xF << 1)
#define AUDIO_ANA_DAC_LOUT_EN_SHIFT		1
#define AUDIO_ANA_DAC_BUF_LOUT_EN_MASK		(0xF << 7)
#define AUDIO_ANA_DAC_BUF_LOUT_EN_SHIFT		7

#define KCODEC_DAC_GAIN_SELECT_FINE		(1 << 15)
#define KCODEC_ADC_GAIN_SELECT_FINE		(1 << 15)

#define KCODEC_CONFIG_DSM_DITHER_EN_MASK	(1 << 7)
#define KCODEC_CONFIG_DSM_DITHER_EN_SHIFT	7

#define KCODEC_CONFIG_DEM_DITHER_CFG_MASK	0x1F
#define KCODEC_CONFIG_DEM_DITHER_CFG_SHIFT	0

#define KCODEC_DAC_X_DC_OFFSET_MASK		0xFF
#define KCODEC_DAC_X_DC_OFFSET_SHIFT		0

/* fields of register KCODEC_CONFIG */
#define KCODEC_ADC_EN				(1 << 1)
#define KCODEC2_CONFIG_ADC_A_EN			(1<<10)
#define KCODEC2_CONFIG_ADC_B_EN			(1<<11)

/* fields of register AUDIO_ANA_REF_CTRL0 */
#define AUDIO_ANA_REF_AUDBIAS_IREF_EN		1
#define AUDIO_ANA_REF_AUDBIAS_IREF_TRIM		(7<<1)
#define AUDIO_ANA_REF_AUDBIAS_VAG_TSADC_EN	(1<<6)
#define AUDIO_ANA_REF_MICBIAS_EN		(1<<7)

/*fields of register AUDIO_REGS_CLK_CTRL */
#define ADC_CLK_EN				(0xF<<2)
#define AUDIO_ANA_CAL_ADC_EN			1
#define AUDIO_ANA_CAL_CLK_EN			(1<<11)

/*fields of register AUDIO_ANA_ADC_CTRL1 */
#define AUDIO_ANA_ADC_CH12_CCAL_SEL_MASK	(0xf<<8)
#define AUDIO_ANA_ADC_CH12_CCAL_SEL_SHIFT	8

#define AUDIO_ANA_ADC_CHANNEL_EN		1
#define AUDIO_ANA_ADC_CHANNEL_DITHER_EN		(1<<1)
#define AUDIO_ANA_ADC_CHANNEL_DWA_EN		(1<<2)
#define AUDIO_ANA_ADC_CHANNEL_GAIN_SEL		(0xf<<3)

/*fields of register AUDIO_ANA_CAL_CTRL0 */
#define AUDIO_ANA_CAL_ADC_EN			1

#define DAC_BASE_SMAPLE_RATE_44K1		0
#define DAC_BASE_SMAPLE_RATE_48K0		1
#define DAC_BASE_SMAPLE_RATE_32K0		2
#define DAC_BASE_SMAPLE_RATE_40K0		3
#define DAC_BASE_SMAPLE_RATE_96K0		4
#define DAC_BASE_SMAPLE_RATE_192K0		5

#define KCODEC_DAC_SELECT_EXT			(1 << 5)
#define KCODEC_DAC_EXT_BASE_SAMP_RATE_SHIFT	6
#define KCODEC_DAC_EXTENDED_BASE_SAMP_RATE_MASK	(0xF << 6)

#define ADC_SAMPLE_RATE_08K			0
#define ADC_SAMPLE_RATE_11K			1
#define ADC_SAMPLE_RATE_12K			10
#define ADC_SAMPLE_RATE_16K			2
#define ADC_SAMPLE_RATE_22K			3
#define ADC_SAMPLE_RATE_24K			4
#define ADC_SAMPLE_RATE_32K			5
#define ADC_SAMPLE_RATE_44K			6
#define ADC_SAMPLE_RATE_48K			8
#define ADC_SAMPLE_RATE_96K			9

#define KCODEC_CONFIG_DEM_DITHER_CFG_MASK	0x1F
#define KCODEC_CONFIG_DEM_DITHER_CFG_SHIFT	0

#define TXADC_IREF_EN				1

#define AUDIO_ANA_CTRL_ADC_EN			1

#define AUDIO_ANA_ADC_CHANNEL_CLK_SEL_DELAY_MASK	(0xF << 7)
#define AUDIO_ANA_ADC_CHANNEL_CLK_SEL_DELAY_SHIFT	7
#define AUDIO_GAIN_MASK					0x1FF

#define AUDIO_ANA_ADC_CHANNEL_GAIN_SEL_MASK	(0xf << 3)
#define AUDIO_ANA_ADC_CHANNEL_GAIN_SEL_SHIFT	3
#define AUDIO_ANA_ADC_MICAMP_GAIN_SEL_MASK	(0xf << 3)
#define AUDIO_ANA_ADC_MICAMP_GAIN		(10 << 3)
#endif /* _SIRF_ATLAS7_CODEC_H */
